<program> ::= <function>
<function> ::= "int" <identifier> "(" ")" "{" <statement> "}"
<statement> ::= "return" <exp> ";"
<exp> ::= <int> | <exp> | "(" <exp> ")"
<identifier> ::= ? identifier token ?
<int> ::= ? constant token ?
