<program> ::= { <declaration> }
<declaration> ::= <variable_declaration> 
                | <array_declaration> 
                | <function_declaration> 

<variable_declaration> ::= <data_type> <identifier> "=" <exp>  { "," <identifier> "=" <exp> } ";" 
                        | <data_type> <identifier> { "," <identifier> } ";" 
<array_declaration> ::= <data_type> <identifier> "[" [ <const> ] "]" [ "=" "{" [ <argument_list> ] "}" ] ";"
<function_declaration> ::= <data_type> <identifier> "(" <parameter_list> ")" ( <block> | ";" )

<parameter_list> ::= ["void"] |  <data_type> <identifier> { "," <data_type> <identifier> }
<argument_list> ::= <const> { "," <const> }

<data_type> ::= "int" | "float" | "char" | "bool"

<block> ::= "{" <block_item_list> "}"
<block_item_list> ::= { <block_item> }
<block_item> ::= <statement> | <variable_declaration> | <array_declaration>

<statement> ::= "return" <const> ";"
              | <const> ";"
              | ";"
              | <block>
              | <for_statement>
              | "while" "(" <const> ")" <block>
              | "for" "(" (<variable_declaration> | <array_declaration> | <const> ";") <const> ";" <const> ")" <block>
              | <if_statement>
              | <input_statement>
              | <outout_statement>

<input_statement> ::= "scanf" "(" <string> { "," "&" <identifier> } ")" ";"
<output_statement> ::= "printf" "(" <string> ")"  
                                    | "printf" "(" <string> "," <const> ")" 
                                    | "printf" "(" <string> { "," <const> } ")" 
                                    | "printf" "(" <identifier> ")"
<if_statement> ::= "if" "(" <const> ")" <block> [<else-clause>]
<else-clause> ::= "else" <block>
                | "else" <if_statement>

<const> ::= <int> | <float> | <char> | <bool>
<string> ::= STRING
<identifier> ::= IDENTIFIER
<int> ::= INTEGER_LITERAL
<float> ::= FLOAT_LITERAL
<char> ::= CHARACTER_LITERAL
<bool> ::= "true" | "false"