Program(
  Declaration(
    Function_Declaration(
      Data_Type(
        int
      ),
      Identifier(
        identifier: "main"
      ),
      left_parenthesis,
      Parameter_List(),
      right_parenthesis,
      Block(
        left_brace,
        Block_Item(
          Statement(
            Expression_Statement(
              Exp(
                Additive(
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "1"
                        )
                      )
                    )
                  ),
                  plus,
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "1"
                        )
                      )
                    )
                  )
                )
              ),
              semicolon
            )
          )
        ),
        Block_Item(
          Statement(
            Expression_Statement(
              Exp(
                Additive(
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "2"
                        )
                      )
                    )
                  ),
                  minus,
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "1"
                        )
                      )
                    )
                  )
                )
              ),
              semicolon
            )
          )
        ),
        Block_Item(
          Statement(
            Expression_Statement(
              Exp(
                Additive(
                  Additive(
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "1"
                          )
                        )
                      )
                    ),
                    plus,
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "1"
                          )
                        )
                      )
                    )
                  ),
                  plus,
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "1"
                        )
                      )
                    )
                  )
                )
              ),
              semicolon
            )
          )
        ),
        Block_Item(
          Statement(
            Expression_Statement(
              Exp(
                Equality(
                  Relational(
                    Additive(
                      Additive(
                        Unary_Exp(
                          Factor(
                            Const(
                              Int(
                                integer_literal: "1"
                              )
                            )
                          )
                        ),
                        plus,
                        Unary_Exp(
                          Factor(
                            Const(
                              Int(
                                integer_literal: "1"
                              )
                            )
                          )
                        )
                      ),
                      minus,
                      Unary_Exp(
                        Factor(
                          Const(
                            Int(
                              integer_literal: "2"
                            )
                          )
                        )
                      )
                    ),
                    greater,
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "1"
                          )
                        )
                      )
                    )
                  ),
                  equal,
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "3"
                        )
                      )
                    )
                  )
                )
              ),
              semicolon
            )
          )
        ),
        right_brace
      )
    )
  )
)