Program(
  Declaration(
    Function_Declaration(
      Data_Type(
        int
      ),
      Identifier(
        identifier: "main"
      ),
      left_parenthesis,
      Parameter_List(),
      right_parenthesis,
      Block(
        left_brace,
        Block_Item_List(
          Block_Item(
            Statement(
              Expression_Statement(
                Exp(
                  Exponent(
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "1"
                          )
                        )
                      )
                    ),
                    exponent,
                    Exponent(
                      Unary_Exp(
                        Factor(
                          Const(
                            Int(
                              integer_literal: "2"
                            )
                          )
                        )
                      ),
                      exponent,
                      Unary_Exp(
                        Factor(
                          Const(
                            Int(
                              integer_literal: "3"
                            )
                          )
                        )
                      )
                    )
                  )
                ),
                semicolon
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Exp(
                  Logical_And(
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "1"
                          )
                        )
                      )
                    ),
                    and,
                    Exponent(
                      Unary_Exp(
                        Factor(
                          Const(
                            Int(
                              integer_literal: "2"
                            )
                          )
                        )
                      ),
                      exponent,
                      Exponent(
                        Unary_Exp(
                          Factor(
                            Const(
                              Int(
                                integer_literal: "3"
                              )
                            )
                          )
                        ),
                        exponent,
                        Exponent(
                          Unary_Exp(
                            Factor(
                              Const(
                                Int(
                                  integer_literal: "4"
                                )
                              )
                            )
                          ),
                          exponent,
                          Unary_Exp(
                            Factor(
                              Identifier(
                                identifier: "func"
                              ),
                              left_parenthesis,
                              right_parenthesis
                            )
                          )
                        )
                      )
                    )
                  )
                ),
                semicolon
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                Identifier(
                  identifier: "a"
                ),
                assign,
                Logical_Or(
                  Unary_Exp(
                    Factor(
                      Const(
                        Int(
                          integer_literal: "1"
                        )
                      )
                    )
                  ),
                  or,
                  Logical_And(
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "2"
                          )
                        )
                      )
                    ),
                    and,
                    Exponent(
                      Unary_Exp(
                        Factor(
                          Const(
                            Int(
                              integer_literal: "3"
                            )
                          )
                        )
                      ),
                      exponent,
                      Unary_Exp(
                        Factor(
                          Const(
                            Int(
                              integer_literal: "4"
                            )
                          )
                        )
                      )
                    )
                  )
                )
              ),
              semicolon
            )
          ),
          Block_Item(
            Statement(
              Exp(
                Identifier(
                  identifier: "a"
                ),
                assign,
                Logical_Or(
                  Exponent(
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "1"
                          )
                        )
                      )
                    ),
                    exponent,
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "2"
                          )
                        )
                      )
                    )
                  ),
                  or,
                  Logical_And(
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "3"
                          )
                        )
                      )
                    ),
                    and,
                    Unary_Exp(
                      Factor(
                        Const(
                          Int(
                            integer_literal: "4"
                          )
                        )
                      )
                    )
                  )
                )
              ),
              semicolon
            )
          )
        ),
        right_brace
      )
    )
  )
)