Program(
  Declaration(
    Function_Declaration(
      Data_Type(
        INT
      ),
      Identifier(
        IDENTIFIER: "main"
      ),
      LEFT_PARENTHESIS,
      Parameter_List(
        VOID
      ),
      RIGHT_PARENTHESIS,
      Block(
        LEFT_BRACE,
        Block_Item_List(
          Block_Item(
            Statement()
          ),
          Block_Item(
            Statement(
              Const_Statement(
                Const(
                  Int(
                    INTEGER_LITERAL: "123123"
                  )
                ),
                SEMICOLON
              )
            )
          )
        ),
        RIGHT_BRACE
      )
    )
  )
)