<statement>
= "if" "(" <exp> ")" <block> [ "else" <block> | <statement> ]
= "if" "(" <exp> ")" <block>  "else" <statement>
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> [ "else" <block> | <statement> ]
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" <block>
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" <block-item-list> "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" <block-item> "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" <statement> "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <exp> ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <unary_exp> ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <unop> <unary_exp> ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <unop> <factor> ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <unop> <const> ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <unop> <int> ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" <unop> 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" <block> "else" "{" "return" - 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" <block-item-list> "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" <block-item> "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" <statement> "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <logical_or_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <logical_and_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <equality_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <relational_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <additive_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <multiplicative_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <power_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <unary_exp> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <factor> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <const> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" <int> ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <logical_or_exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <logical_and_exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <relational_exp>  ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <additive_exp>")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <multiplicative_exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <power_exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <unary_exp> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <factor> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <const> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" <int> ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <equality_exp> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <relational_exp> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <additive_exp> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <multiplicative_exp> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <power_exp> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <unary_exp> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <factor> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" <identifier> "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" <block>  "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "}"  "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> <block-item> "}"  "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> <statement>" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <logical_and_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <equality_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <relational_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <additive_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <multiplicative_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <power_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <unary_exp>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <factor>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <const>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" <int>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item-list> "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <block-item> "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <declaration> "return" <int>";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <variable_declaration> "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <data_type> <identifier> ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <exp> ")" "{" <data_type> a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <logical_or_exp> ")" "{" "int" a";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <logical_and_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <equality_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <additive_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <multiplicative_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <power_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <unary_exp> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <factor> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <const> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" <int> ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <relational_exp> ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <additive_exp> ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <multiplicative_exp> ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <unary_exp> ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <factor> ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" <identifier> ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
= "if" "(" z ">" 10 ")" "{" "int" a ";" "return" 1 ";" "}" "else" "if" "(" z "==" 10 ")" "{" "return" 0 ";" "}" "else" "{" "return" "-" 1 ";" "}"
