<statement>
= <if_statement>
= "if" "(" <exp> ")" <block> [ <else_clause> ]
= "if" "(" <exp> ")" <block> <else_clause>
= "if" "(" <exp> ")" <block> "else" <if_statement>
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> [ <else_clause> ]
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> <else_clause>
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" <if_statement>
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> [ <else_clause> ]
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> <else_clause>
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" <block>
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "{" <block_item_list> "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "{" <block_item> "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "{" <variable_declaration> "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "{" <data_type> <identifier> ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "{" bool <identifier> ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <block_item_list> "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <block_item> "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <variable_declaration> "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <data_type> <identifier> ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" float <identifier> ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <logical_or_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <logical_and_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <additive_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <multiplicative_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <power_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <unary_exp> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <factor> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <const> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" <int> ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <additive_exp> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <multiplicative_exp> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <power_exp> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <unary_exp> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <factor> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" <identifier> "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" <block> "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <block_item_list> "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <block_item> "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <variable_declaration> "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <data_type> <identifier> ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" <data_type> b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <logical_or_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <logical_and_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <relational_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <additive_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <multiplicative_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <power_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <unary_exp> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <factor> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <const> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" <int> ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <equality_exp> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <relational_exp> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <additive_exp> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <multiplicative_exp> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <power_exp> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <unary_exp> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <factor> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" <identifier> "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" <block> "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" "{" <block_item_list> "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" "{" <block_item> "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" "{" <variable_declaration> "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" "{" <data_type> <identifier> ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" "{" <data_type> a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <logical_or_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <logical_and_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <equality_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <additive_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <multiplicative_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <power_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <unary_exp> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <factor> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <const> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" <int> ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <relational_exp> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <additive_exp> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <multiplicative_exp> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <power_exp> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <unary_exp> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <factor> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" <identifier> ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"
= "if" "(" z ">" 10 ")" "{" int a ";" "}" "else" "if" "(" z "==" 10 ")" "{" char b ";" "}" "else" "if" "(" z "<" 10 ")" "{" float c ";" "}" "else" "{" bool d ";" "}"