[##\<statement\>
  [##\<if\_statement\>
    [##if]
    [##(]
    [##\<exp\>
      [##\<logical\_or\_exp\>
        [##\<logical\_and\_exp\>
          [##\<equality\_exp\>
            [##\<relational\_exp\>
              [##\<relational\_exp\>
                [##\<additive\_exp\>
                  [##\<multiplicative\_exp\>
                    [##\<power\_exp\>
                      [##\<unary\_exp\>
                        [##\<factor\>
                          [##\<identifier\>
                            [##z]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
              [##\>]
              [##\<additive\_exp\>
                [##\<multiplicative\_exp\>
                  [##\<power\_exp\>
                    [##\<unary\_exp\>
                      [##\<factor\>
                        [##\<const\>
                          [##\<int\>
                            [##10]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
    [##)]
    [##\<block\>
      [##\{]
      [##\<block\_item\_list\>
        [##\<block\_item\>
          [##\<variable\_declaration\>
            [##\<data\_type\>
              [##int]
            ]
            [##\<identifier\>
              [##a]
            ]
            [##\;]
          ]
        ]
      ]
      [##\}]
    ]
    [##\<else\_clause\>
      [##else]
      [##\<if\_statement\>
        [##if]
        [##(]
        [##\<exp\>
          [##\<logical\_or\_exp\>
            [##\<logical\_and\_exp\>
              [##\<equality\_exp\>
                [##\<equality\_exp\>
                  [##\<relational\_exp\>
                    [##\<additive\_exp\>
                      [##\<multiplicative\_exp\>
                        [##\<power\_exp\>
                          [##\<unary\_exp\>
                            [##\<factor\>
                              [##\<identifier\>
                                [##z]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
                [##\=\=]
                [##\<relational\_exp\>
                  [##\<additive\_exp\>
                    [##\<multiplicative\_exp\>
                      [##\<power\_exp\>
                        [##\<unary\_exp\>
                          [##\<factor\>
                            [##\<const\>
                              [##\<int\>
                                [##10]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
        [##)]
        [##\<block\>
          [##\{]
          [##\<block\_item\_list\>
            [##\<block\_item\>
              [##\<variable\_declaration\>
                [##\<data\_type\>
                  [##char]
                ]
                [##\<identifier\>
                  [##b]
                ]
                [##\;]
              ]
            ]
          ]
          [##\}]
        ]
        [##\<else\_clause\>
          [##else]
          [##\<if\_statement\>
            [##if]
            [##(]
            [##\<exp\>
              [##\<logical\_or\_exp\>
                [##\<logical\_and\_exp\>
                  [##\<equality\_exp\>
                    [##\<relational\_exp\>
                      [##\<relational\_exp\>
                        [##\<additive\_exp\>
                          [##\<multiplicative\_exp\>
                            [##\<power\_exp\>
                              [##\<unary\_exp\>
                                [##\<factor\>
                                  [##\<identifier\>
                                    [##z]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                      [##\<]
                      [##\<additive\_exp\>
                        [##\<multiplicative\_exp\>
                          [##\<power\_exp\>
                            [##\<unary\_exp\>
                              [##\<factor\>
                                [##\<const\>
                                  [##\<int\>
                                    [##10]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
            [##)]
            [##\<block\>
              [##\{]
              [##\<block\_item\_list\>
                [##\<block\_item\>
                  [##\<variable\_declaration\>
                    [##\<data\_type\>
                      [##float]
                    ]
                    [##\<identifier\>
                      [##c]
                    ]
                    [##\;]
                  ]
                ]
              ]
              [##\}]
            ]
            [##\<else\_clause\>
              [##else]
              [##\<block\>
                [##\{]
                [##\<block\_item\_list\>
                  [##\<block\_item\>
                    [##\<variable\_declaration\>
                      [##\<data\_type\>
                        [##bool]
                      ]
                      [##\<identifier\>
                        [##d]
                      ]
                      [##\;]
                    ]
                  ]
                ]
                [##\}]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
]