[##\<statement\>
  [##<>if<>]
  [##<>(<>]
  [##\<exp\>
    [##\<logical\_or\_exp\>
      [##\<logical\_and\_exp\>
        [##\<equality\_exp\>
            [##\<relational\_exp\>
              [##\<relational\_exp\
                [##\<additive\_exp\>
                  [##\<multiplicative\_exp\>
                    [##\<power\_exp\>
                      [##\<unary\_exp\>
                        [##\<factor\>
                          [##\<identifier\>
                            [##<>z<>]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
              [##<>\><>]
              [##\<additive\_exp\>
                [##\<multiplicative\_exp\>
                  [##\<power\_exp\>
                    [##\<unary\_exp\>
                      [##\<factor\>
                        [##\<const\>
                          [##\<int\>
                            [##<>10<>]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
        ]
      ]
    ]
  ]
  [##<>)<>]
  [##\<block\>
    [##<>\{<>]
    [##\<block\-item\-list\>
      [##\<block\-item\-list\>
        [##\<block\_item\>
          [##\<declaration\>
            [##\<variable\_declaration\>
              [##\<data\_type\>
                [##<>int<>]
              ]
              [##\<identifier\>
                [##<>a<>]
              ]
              [##<>;<>]
            ]
          ]
        ]
      ]
      [##\<block\_item\>
        [##\<statement\>
          [##<>return<>]
          [##\<exp\>
            [##\<logical\_or\_exp\>
              [##\<logical\_and\_exp\>
                [##\<equality\_exp\>
                  [##\<relational\_exp\>
                    [##\<additive\_exp\>
                      [##\<multiplicative\_exp\>
                        [##\<power\_exp\>
                          [##\<unary\_exp\>
                            [##\<factor\>
                              [##\<const\>
                                [##\<int\>
                                  [##<>1<>]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
          [##<>;<>]
        ]
      ]
    ]
    [##<>\}<>]
  ]
  [##<>else<>]
  [##\<statement\>
    [##<>if<>]
    [##<>(<>]
    [##\<exp\>
      [##\<logical\_or\_exp\>
        [##\<logical\_and\_exp\>
          [##\<equality\_exp\>
            [##\<equality\_exp\>
                [##\<relational\_exp\>
                  [##\<additive\_exp\>
                    [##\<multiplicative\_exp\>
                      [##\<power\_exp\>
                        [##\<unary\_exp\>
                          [##\<factor\>
                            [##\<identifier\>
                              [##<>z<>]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
              [##<>\=\=<>]
              [##\<relational\_exp\>
                [##\<additive\_exp\>
                  [##\<multiplicative\_exp\>
                    [##\<power\_exp\>
                      [##\<unary\_exp\>
                        [##\<factor\>
                          [##\<const\>
                            [##\<int\>
                              [##<>10<>]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
        ]
      ]
    ]
    [##<>)<>]
    [##\<block\>
      [##<>\{<>]
      [##\<block\-item\-list\>
        [##\<block\_item\>
          [##\<statement\>
            [##<>return<>]
            [##\<exp\>
              [##\<logical\_or\_exp\>
                [##\<logical\_and\_exp\>
                  [##\<equality\_exp\>
                    [##\<relational\_exp\>
                      [##\<additive\_exp\>
                        [##\<multiplicative\_exp\>
                          [##\<power\_exp\>
                            [##\<unary\_exp\>
                              [##\<factor\>
                                [##\<const\>
                                  [##\<int\>
                                    [##<>0<>]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
            [##<>;<>]
          ]
        ]
      ]
      [##<>\}<>]
    ]
    [##<>else<>]
    [##\<block\>
      [##<>\{<>]
      [##\<block\-item\-list\>
        [##\<block\_item\>
          [##\<statement\>
            [##<>return<>]
            [##\<exp\>
              [##\<logical\_or\_exp\>
                [##\<logical\_and\_exp\>
                  [##\<equality\_exp\>
                    [##\<relational\_exp\>
                      [##\<additive\_exp\>
                        [##\<multiplicative\_exp\>
                          [##\<power\_exp\>
                            [##\<unary\_exp\>
                              [##\<unop\>
                                [##<>\-<>]
                              ]
                              [##\<unary\_exp\>
                                [##\<factor\>
                                  [##\<const\>
                                    [##\<int\>
                                      [##<>1<>]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
            [##<>;<>]
          ]
        ]
      ]
      [##<>\}<>]
    ]
  ]
]