[##\<block\>
  [##\<block\_item\_list\>
    [##\<block\_item\>
      [##\<statement\>
        [##\<input\_statement\>
          [##<>scanf<>]
          [##<>(<>]
          [##\<string\>
            [##<>"%f<>%f"<>]
          ]
          [##<>,<>]
          [##<>&<>]
          [##\<identifier\>
            [##<>&value1<>]
          ]
          [##<>,<>]
          [##<>&<>]
          [##\<identifier\>
            [##<>&value2<>]
          ]
          [##<>)<>]
          [##<>;<>]
        ]
      ]
    ]
  ]
]